image: gitpod/workspace-mongodb

tasks:
  - init: yarn install
    command: yarn run build
  - init: cd client && yarn install
    command: yarn run react:dev-cloud
  
ports:
  - port: 3000
    onOpen: open-preview