image: gitpod/workspace-mongodb

tasks:
  - init: |
      touch /tmp/.npm-lock
      yarn install
      rm /tmp/.npm-lock
    command: yarn run dev
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      # This part is needed for the cloud environment
      echo "DANGEROUSLY_DISABLE_HOST_CHECK=true" >> ./client/.env.development.local
      yarn run react:dev
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  
ports:
  - port: 3000
    onOpen: open-preview